- elfmalloc/src/slag.rs
Running tests without `release` uncovered this issue where we were overflowing a `usize`. The standard wrapping behavior is intended in this case, but we need to explicitly opt into it to avoid UB.
> Fix small overflow bug in coalescer "hash function".

- elfmalloc/Cargo.toml
- elfmalloc/src/alloc_impl.rs
- elfmalloc/src/general.rs
- elfmalloc/src/lib.rs
This is a first step towards supporting the emerging Rust `Alloc` ecosystem, as well as supporting auto-genned C hooks via `malloc_bind`.
Part of doing this is to get a working `realloc` implementation: that hasn't really been our focus but it is worth giving this attention. The one on master right now is *probably* correct, but it is relatively untested. It also does not support passing a new alignment parameter, which `Alloc` requires.
> Implement Alloc Traits

- mmap-alloc/Cargo.toml
- mmap-alloc/src/lib.rs
Generally, this commit drives towards embracing that we expose platform-specific behavior, and chooses to expose that reality rather than trying to present a cross-platform abstraction that will inevitably leak.
- Remove commit on Linux and Mac
- Add commit and uncommit on Windows
- Add the ability to configure whether `alloc` commits
> mmap-alloc: Support committing and uncommitting on Windows

- malloc-bind/CHANGELOG.md
- malloc-bind/README.md
- malloc-bind/src/lib.rs
This PR contains a number of fixes for bugs and TODOs relating to matching the semantics of the C API (which is made particularly tricky by differing behavior across platforms). It also adds support for the windows `_aligned_malloc` function.
Closes #8.
> malloc-bind: Match exact semantics of the C API

- mmap-alloc/CHANGELOG.md
- mmap-alloc/src/lib.rs
The remainder should be subtracted from the unit, not the size: e.g.
```rust
next_multiple(4, 4096); // returns 4
next_multiple(10000, 4096); // returns 18192
```
> Fix next_multiple for mmap-alloc

- bsalloc/CHANGELOG.md
- bsalloc/src/bsalloc.rs
- bsalloc/src/lib.rs
Instead of always `expect`-ing a successful allocation from mmap-alloc,
propagate AllocErrs up to the user. 
Fixes #4
> Make bsalloc propagate allocation failures from mmap-alloc

- mmap-alloc/CHANGELOG.md
- mmap-alloc/src/lib.rs
We implement the `usable_size` function, which allows us to implement
`alloc`/`dealloc`, and get correct implementations of `alloc_excess`,
`grow_in_place`, and `shrink_in_place` for free.
Additionally, for linux, we implement `realloc`, `grow_in_place`, and
`shrink_in_place` using `mremap`.
Fixes #9 
Open Questions:
- When allocating with mmap, we check if mmap returns a null pointer, and handle that case. Currently, this implementation panics if mremap returns a null pointer. Should we handle this case?
- As far as I can tell, the only way to recover is to to make another mmap, and memcpy (which may not even handle null pointers? we might be really fighting the optimizer no mater what we do), or try to pre-map a page at 0 manually beforehand).
- Posix specifies [for …
> mmap-alloc: Support the full Alloc API

- elfmalloc/src/utils.rs
- mmap-alloc/CHANGELOG.md
- mmap-alloc/Cargo.toml
- mmap-alloc/appveyor.sh
- mmap-alloc/src/lib.rs
- mmap-alloc/src/tests.rs
- mmap-alloc/travis.sh
- Add the ability to parse `/proc/<pid>/maps` on Linux, and incorporate this into existing tests in order to verify permissions
- Remove checks for allocation at the 0 page, as it turns out that these are unnecessary on all platforms that we support (Linux, Mac, Windows)
- Change the way boolean configuration functions work for `MapAllocBuilder` (instead of `xxx()` and `no_xxx()`, we now supply a single `xxx(xxx: bool)` method that accepts a boolean indicating whether the configuration should be on or off)
- Move tests module into separate file
Closes #83.
Closes #72 and #80 by making them unnecessary since this commit removes the use cases for `mark_unused` and `alloc_helper`.
For posterity: A previous version of the code to verify memory permissions attempted to access a region in order …
> mmap-alloc: Improve tests for permissions, fix realloc bugs

- elfmalloc/travis.sh
Even though we're not running elfmalloc tests on Travis, we should still build to detect compilation failures.
> elfmalloc, Travis: Build elfmalloc (don't test) on Travis

- info/custom-vec.md
Since the latest push, a couple things in here are outdated. They should be fixed now
> info: Fix outdated docs for Vec writeup

- object-alloc-test/Cargo.toml
- object-alloc-test/src/lib.rs
- slab-alloc/Cargo.toml
- Upgrade to `interpolate_idents` 0.1.8
- Add `#![feature(const_size_of)]` to `object-alloc-test`
Closes #91
> object-alloc-test, slab-alloc: Upgrade to interpolate_idents 0.1.8

- mmap-alloc/CHANGELOG.md
- mmap-alloc/src/lib.rs
- mmap-alloc/src/tests.rs
Remove huge page support, as huge pages are only supported on Linux and Windows, and do not play nicely with other features we use. For example, on Linux, you can't uncommit (`MADV_DONTNEED`) a mapping created with huge pages, and on Windows, you cannot create a mapping with huge pages without also committing them at the same time.
Closes #50
> mmap-alloc: Remove huge page support

- alloc-fmt/CHANGELOG.md
- alloc-fmt/Cargo.toml
- alloc-fmt/README.md
- alloc-fmt/appveyor.sh
- alloc-fmt/src/bin/assert.rs
- alloc-fmt/src/bin/print.rs
- alloc-fmt/src/lib.rs
- alloc-fmt/travis.sh
- bsalloc/Cargo.toml
- bsalloc/src/lib.rs
- elfmalloc/Cargo.toml
- elfmalloc/src/alloc_impl.rs
- elfmalloc/src/frontends.rs
- elfmalloc/src/general.rs
- elfmalloc/src/lib.rs
- elfmalloc/src/rust_alloc.rs
- elfmalloc/src/slag.rs
- elfmalloc/src/sources.rs
- elfmalloc/src/utils.rs
- elfmalloc/src/vec_alloc.rs
This new `alloc-fmt` crate provides formatting macros equivalent to the standard library's macros, except they don't allocate. I had long suspected that this might be an issue, but I finally came across a bug in PR #85 that is caused by this problem, so I figured it was finally time to address the it.
> Add alloc-fmt crate for allocation-safe formatting and output

- mmap-alloc/travis.sh
Now that https://github.com/rust-lang/rust/pull/45866 has landed in nightly, re-enable tests to see if they work now.
> mmap-alloc: Re-enable Travis tests on Mac

- malloc-bind/CHANGELOG.md
- malloc-bind/src/lib.rs
This PR is a possible solution for #111. Actually, I hadn't found use cases for "likely", so I've put "unlikely" only.
I've put "unlikely" to "unhappy" paths, like NULL on free() and erroneous arguments in "posix_memalign". The motivation behind the second example is that the code not checking its arguments beforehand may be punished in terms of performance.
> Malloc bind unlikely

- .travis.yml
Since Travis switched to XCode8.3 as the default for Mac builds, we need to use `pip2` instead of `pip`.
> Travis: Use pip2 instead of pip now that XCode8.3 is default

- bsalloc/Cargo.toml
- elfmalloc/Cargo.toml
- malloc-bind/Cargo.toml
- object-alloc-test/Cargo.toml
- slab-alloc/Cargo.toml
Hey
Upgraded lazy-static to 1.0.0. I have run the test suites of each sub-repository where the change has been made there is no breaking change in switch from 0.2.9 to 1.0.0. 
Fixes #138
> Cargo.toml : upgrade lazy-static to 1.0.0

- mmap-alloc/CHANGELOG.md
- mmap-alloc/Cargo.toml
- mmap-alloc/src/lib.rs
- object-alloc-test/CHANGELOG.md
- object-alloc-test/Cargo.toml
- object-alloc-test/src/corruption.rs
- object-alloc-test/src/leaky_alloc.rs
- object-alloc-test/src/lib.rs
- object-alloc/CHANGELOG.md
- object-alloc/src/lib.rs
- slab-alloc/CHANGELOG.md
- slab-alloc/Cargo.toml
- slab-alloc/src/aligned.rs
- slab-alloc/src/backing.rs
- slab-alloc/src/init.rs
- slab-alloc/src/large.rs
- slab-alloc/src/lib.rs
- slab-alloc/src/ptr_map.rs
- slab-alloc/src/stack.rs
- slab-alloc/src/tests.rs
- slab-alloc/src/util.rs
- slab-alloc/travis.sh
- Switch from `*mut u8` and `*mut T` to `NonNull<u8>` and `NonNull<T>` in trait methods
- Upgrade `slab-alloc`, `mmap-alloc`, and `object-alloc-test` accordingly
- Closes #140
> object-alloc: Switch from *mut to NonNull

- CONTRIBUTING.md
- test-scripts/check-copyright-comments.sh
Catch errors where the correct year is X but the copyright comment says "Copyright X-Y".
> test-scripts/check-copyright-comments.sh: Catch more errors

- alloc-fmt/CHANGELOG.md
- alloc-fmt/src/bin/assert.rs
- alloc-fmt/src/lib.rs
- Add `AllocUnwrap` trait, which provides `alloc_unwrap` and `alloc_expect` and is implemented for `Option` and `Result`
- Refactor `alloc_panic` to use a function like the stdlib. This allows us to mark that function as `#[cold]` and `#[inline(never)]`, hopefully reducing the inline size of the `alloc_panic` macro and also improving branch prediction.
> alloc-fmt: Add AllocUnwrap trait, refactor alloc_panic macro

- elfmalloc/Cargo.toml
- elfmalloc/src/rust_alloc.rs
- elfmalloc/travis.sh
We've previously had an issue with running out of memory during Travis tests, so this PR forces the tests to run sequentially to reduce the maximum working set size and reduces the size of certain tests when running in Travis via the `low-memory-tests` feature.
> elfmalloc: Re-enable Travis tests, set RUST_TEST_THREADS=1

- mmap-alloc/CHANGELOG.md
- mmap-alloc/Cargo.toml
- mmap-alloc/appveyor.sh
- mmap-alloc/src/lib.rs
- mmap-alloc/src/tests.rs
- mmap-alloc/travis.sh
- Add `large-align` feature, allowing alignments larger than a page size
- Allow memory to be explicitly committed on Linux and Mac
- Allow memory to be committed on allocation on Mac
- Improve documentation around committed/uncommitted memory
- Closes #151
> mmap-alloc: Add large-align feature, support committing on Linux/Mac

- mmap-alloc/CHANGELOG.md
- mmap-alloc/src/lib.rs
- mmap-alloc/src/tests.rs
This PR supersedes #181 (it contains the same commit as #181, plus a new one to handle further changes to the `Alloc` trait which landed after that PR was posted).
@fitzgen heads up about this since it affects wee_alloc.
> mmap-alloc: Update to new Alloc trait

- alloc-tls/src/lib.rs
- elfmalloc/Cargo.toml
- elfmalloc/src/alloc_impl.rs
- elfmalloc/src/rust_alloc.rs
- elfmalloc/src/sources.rs
- elfmalloc/src/utils.rs
- elfmalloc/src/vec_alloc.rs
- malloc-bind/src/lib.rs
- mmap-alloc/src/lib.rs
- object-alloc-test/src/lib.rs
- object-alloc/src/lib.rs
- slab-alloc/src/backing.rs
- slab-alloc/src/lib.rs
- slab-alloc/src/util.rs
- Update from `alloc::allocator` to `alloc::alloc` module
- Remove stabilized or unrecognized features
> Upgrade stdlib dependencies

- object-alloc-test/Cargo.toml
- object-alloc-test/src/lib.rs
- object-alloc-test/src/types.rs
- slab-alloc/Cargo.toml
- slab-alloc/src/lib.rs
cc https://github.com/SkylerLipthay/interpolate_idents/issues/45
> object-alloc-test: Use paste instead of interpolate_idents
